providers = ["staticfile"]


[phases.install]
aptPkgs = ['build-essential']
nixPkgs = ['rustup']
cmds = ["rustup default nightly", "rustup target add wasm32-unknown-unknown"]

[phases.setup]
# nixOverlays = [
# 'https://github.com/mozilla/nixpkgs-mozilla/archive/master.tar.gz',
# ]


[phases.build]
nixPkgs = ['trunk']
cmds = ['./build.sh']
