providers = ["staticfile"]


[phases.install]
aptPkgs = ['build-essential']
nixPkgs = ['rustup']
cmds = ["rustup default nightly", "rustup target add wasm32-unknown-unknown"]


[phases.build]
nixPkgs = ['trunk']
cmds = ['./build.sh']
