use crate::mooneye_tests;
use crate::test::util::mooneye_test::run_mooneye_test;

mooneye_tests! {
	add_sp_e_timing:"mooneye/acceptance/timing/add_sp_e_timing",
	call_cc_timing:"mooneye/acceptance/timing/call_cc_timing",
	call_cc_timing2:"mooneye/acceptance/timing/call_cc_timing2",
	call_timing:"mooneye/acceptance/timing/call_timing",
	call_timing2:"mooneye/acceptance/timing/call_timing2",
	di_timing:"mooneye/acceptance/timing/di_timing-GS",
	div_timing:"mooneye/acceptance/timing/div_timing",
	ei_sequence:"mooneye/acceptance/timing/ei_sequence",
	ei_timing:"mooneye/acceptance/timing/ei_timing",
	halt_ime0_ei:"mooneye/acceptance/timing/halt_ime0_ei",
	halt_ime0_nointr_timing:"mooneye/acceptance/timing/halt_ime0_nointr_timing",
	halt_ime1_timing:"mooneye/acceptance/timing/halt_ime1_timing",
	halt_ime1_timing2:"mooneye/acceptance/timing/halt_ime1_timing2-GS",
	if_ie_registers:"mooneye/acceptance/timing/if_ie_registers",
	intr_timing:"mooneye/acceptance/timing/intr_timing",
	jp_cc_timing:"mooneye/acceptance/timing/jp_cc_timing",
	jp_timing:"mooneye/acceptance/timing/jp_timing",
	ld_hl_sp_e_timing:"mooneye/acceptance/timing/ld_hl_sp_e_timing",
	oam_dma_restart:"mooneye/acceptance/timing/oam_dma_restart",
	oam_dma_start:"mooneye/acceptance/timing/oam_dma_start",
	oam_dma_timing:"mooneye/acceptance/timing/oam_dma_timing",
	pop_timing:"mooneye/acceptance/timing/pop_timing",
	push_timing:"mooneye/acceptance/timing/push_timing",
	rapid_di_ei:"mooneye/acceptance/timing/rapid_di_ei",
	ret_cc_timing:"mooneye/acceptance/timing/ret_cc_timing",
	ret_timing:"mooneye/acceptance/timing/ret_timing",
	reti_intr_timing:"mooneye/acceptance/timing/reti_intr_timing",
	reti_timing:"mooneye/acceptance/timing/reti_timing",
	rst_timing:"mooneye/acceptance/timing/rst_timing",
	bits_reg_f:"mooneye/acceptance/bits/reg_f",
	bits_mem_oam:"mooneye/acceptance/bits/mem_oam",
}
