[package]
name = "sm83"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
lazy_static = "1.4.0"
serde_json = "1.0.91"
log = "0.4.17"
